#数据库相关
spring:
  datasource:
    url: jdbc:mysql://117.50.101.104:3306/test1?characterEncoding=UTF-8
    username: aaa
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #邮箱验证码相关
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 1727035918@qq.com
    password: fjfvlixvtnyqdjfh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#mybatis相关
mybatis:
  type-aliases-package: com.competition.travel.bean
  mapper-locations: classpath\:mapper/*.xml
server:
  port: 9002